name: "My Cash App"
version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:9
    container_name: MySQL
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: my_cash
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - my_cash_network
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
#      timeout: 20s
#      retries: 10

  # Node  Application
  app:
    build: .
    container_name: API
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_NAME=my_cash
    depends_on:
      - mysql
#      mysql:
#        condition: service_healthy
    volumes:
      - api-volume:/app
      - /app/node_modules
    networks:
      - my_cash_network
    command: npm run start:dev -L

volumes:
  db-volume:
  api-volume:

networks:
  my_cash_network:
    driver: bridge